# Generated by Django 3.2.8 on 2022-01-03 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=250)),
                ('contenu', models.TextField()),
                ('slug', models.SlugField(max_length=150)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
    ]
