# Generated by Django 3.2.8 on 2022-01-07 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art24', '0003_articles_secondaire'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='articles_principale',
            name='titre',
        ),
        migrations.RemoveField(
            model_name='articles_secondaire',
            name='titre',
        ),
    ]
