# Generated by Django 4.0.1 on 2022-01-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art24', '0004_auto_20220107_1615'),
    ]

    operations = [
        migrations.CreateModel(
            name='Derniers_Articles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenu', models.TextField()),
                ('slug', models.SlugField(max_length=150)),
                ('date_publication', models.DateTimeField(auto_now_add=True)),
                ('images', models.ImageField(default='default.jpg', upload_to='')),
            ],
        ),
    ]
