# Generated by Django 3.2.8 on 2022-01-17 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art24', '0006_articles_principale_information_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articles_principale',
            name='information',
        ),
        migrations.RemoveField(
            model_name='articles_principale',
            name='titre',
        ),
    ]
