# Generated by Django 3.2.8 on 2022-01-17 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art24', '0007_auto_20220117_1339'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Derniers_Articles',
        ),
    ]
